name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: node:23-alpine

    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build . --file Dockerfile.ci --tag warstats-app:$(date +%s)
